### ISSUE TITLE
Cohort members to group doesn't get imported

### ISSUE THREAD

**Issue by aaloise** [emeneo/moodle-local_course_templates#1]
I have several courses templates, and tried to configure on each one the possibility to have "Cohort members to group", so this type of enrolment gets imported on every new course using the template. But every time a new course arrives I have to configure it again.

Bottom line is that "Cohort members to group" doesn't get imported on new courses.

Using Moodle 3.3.3 and Course templates Version 3.4-a

**Comment by Flottertotte** [comment]
Please try if the following:

1. Backup one of your courses (including the "Cohort members to group" plugin). See https://docs.moodle.org/31/en/Course_backup in case you are not sure how to do this.
2. Restore it as a new course.
3. Check if "Cohort members to group" is included and configured properly in the restored course.

Please report me back the result.

**Comment by aaloise** [comment]
Tried to backup and the restore the course. Cohort members to group didn't appear in the new course either.

**Comment by Flottertotte** [comment]
Thanks for the feedback! My plugin relies on the moodle core function "backup and restore". If a plugin does not supports this, it won't work either with my plugin. 

One way to solve this problem would be to make "Cohort members to group" to work with that function. If you like, I can add such function to "Cohort members to group". You can contact me @ flottertotte@emeneo.com for further details (development work won't  be too big, but it would be a paid service).
