### ISSUE TITLE
window.onload overwritten in process.js

### ISSUE THREAD

**Issue by biwano** [emeneo/moodle-local_course_templates#10]
Hello,

I had an issue when another plugin was declaring another `window.onload=` statement. Thus making the process.js in the course template plugin failing to add a click event listener on the continue event.

i modified the `window.onload` statement with a `$( document ).ready(function() {` statement to make it work.

Can you integrate this change (or one of the same kind) in te next release?

Thanks

**Comment by Flottertotte** [comment]
Thank you! Could you please send the original line of code and the related changed line of code? Even better would be you send a pull request.
Thanks again! Flotter

**Comment by brunoilponseisae** [comment]
Lazy me was afraid you would sayh that :)
Here you go: https://github.com/emeneo/moodle-local_course_templates/pull/11

**Comment by Flottertotte** [comment]
Thank you!
