### ISSUE TITLE
Duplicate admin page name: local_course_templates

### ISSUE THREAD

**Issue by dsbellcom** [emeneo/moodle-local_course_templates#8]
After update to 3.6-a version I have got the error shown bellow:

> Duplicate admin page name: local_course_templates
> line 922 of /lib/adminlib.php: call to debugging()
> line 45 of /local/course_templates/settings.php: call to admin_category->add()
> line 67 of /lib/classes/plugininfo/local.php: call to include()
> line 666 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
> line 8363 of /lib/adminlib.php: call to require()
> line 8250 of /lib/adminlib.php: call to admin_get_root()
> line 33 of /admin/purgecaches.php: call to admin_externalpage_setup()
> Navigation node intersect: Adding a node that already exists local_course_te

> 
> mplates
> line 942 of /lib/navigationlib.php: call to debugging()
> line 388 of /lib/navigationlib.php: call to navigation_node_collection->add()
> line 364 of /lib/navigationlib.php: call to navigation_node->add_node()
> line 4345 of /lib/navigationlib.php: call to navigation_node->add()
> line 4363 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
> line 4363 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
> line 4314 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
> line 4169 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
> line 759 of /lib/pagelib.php: call to settings_navigation->initialise()
> line 820 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
> line 8297 of /lib/adminlib.php: call to moodle_page->__get()
> line 33 of /admin/purgecaches.php: call to admin_externalpage_setup()

I think it is a bug in /local/course_templates/settings.php
may be 'else' is missing there. 
```
if ($hassiteconfig) {
	$settings = new admin_settingpage('local_course_templates','Course templates');
	$ADMIN->add('localplugins',$settings );
    $options = array(1=>get_string('jumpto_coursepage', 'local_course_templates'),2=>get_string('jumpto_coursesettingspage', 'local_course_templates'));
	$settings->add(new admin_setting_configselect('local_course_templates/jump_to', get_string('jumpto', 'local_course_templates'),'', 1, $options));
}else{

$settings = new admin_externalpage('local_course_templates', get_string('addcourse', 'local_course_templates'),new moodle_url('/local/course_templates/index.php'));
$ADMIN->add('localplugins',$settings);
$settings = null;
}
```

**Comment by davidpesce** [comment]
I'm seeing the same on Moodle 3.5+

**Comment by Flottertotte** [comment]
The problem has been fixed.
