### ISSUE TITLE
GDPR compatibility

### ISSUE THREAD

**Issue by OlenaTatarintseva** [emeneo/moodle-local_course_templates#9]
Hello, 
​
It looks like the plugin local_course_templates is not compliant with GDPR. The plugin does not implement the Privacy API.
​
​Best regards,
Olena Tatarintseva

**Comment by Flottertotte** [comment]
Hello Olena and everyone. 

If you need this feature to be realized, one way is to send a development request at www.emeneo.com/support 

Hope that helps :)
